### ISSUE TITLE
Armed nade duplication

### ISSUE THREAD

**Issue by FluffyEevee** [ZehM4tt/Lambda#3]
Hold grenade, unpin and wait a few seconds, kill self and you generates a dozen ticking nades on death. Tested on a locally hosted server with 4 players and p2p.
Also happens on a dedicated server.

Only happens as last player.

No other addons.

**Comment by FluffyEevee** [comment]
Also, no other addons except the gamemode.

**Comment by ZehM4tt** [comment]
For some reason using ply:DropWeapon in DoPlayerDeath seems to cause this. Moved all the code to PlayerDeath which seems to solve this issue.
