### ISSUE TITLE
User never signaled connection

### ISSUE THREAD

**Issue by FluffyEevee** [ZehM4tt/Lambda#5]
Unknown reason, dedicated server. First time joining create this error and stops the player from doing anything except being in a weird state of spectating. Until map restart, changelevel or just round restart.
![ss 2017-01-03 at 08 29 43](https://cloud.githubusercontent.com/assets/9823203/21622146/61bae524-d1fc-11e6-91a1-0896eb9db46a.png)

Dedicated server, no other addons.

Edit: Happens every time after restarting the dedicated server.
Edit2: Seems to also happen randomly but it did on d3_c17_04

**Comment by ZehM4tt** [comment]
Can you use "lambda_log all" and post a clean log when this is happening. I'm trying to reproduce this without success.

**Comment by FluffyEevee** [comment]
https://dl.dropboxusercontent.com/u/17687819/random%20shit/console.log

**Comment by ZehM4tt** [comment]
Thanks, that certainly helps. Seems like you are timing out for no reason handled by the gamemode. I will look into it.

**Comment by ZehM4tt** [comment]
Fixed in next upcoming update
