### ISSUE TITLE
Gamemode doesn't recognize console as admin

### ISSUE THREAD

**Issue by FluffyEevee** [ZehM4tt/Lambda#6]
Self explanatory, dedicated server.

Server doesn't recognize the lambda_restart and probably any other commands if typed from the server console and not in game.
![ss 2017-01-04 at 01 07 27](https://cloud.githubusercontent.com/assets/9823203/21642135/a6f92c20-d280-11e6-8243-beb53ec58a8a.png)

**Comment by knoxed** [comment]
Fixed.

Will be pushed out in a bigger update very soon.

Thanks
