### ISSUE TITLE
Ammo 'management'

### ISSUE THREAD

**Issue by FluffyEevee** [ZehM4tt/Lambda#7]
When you have full total ammo with a weapon you are still able to loot the ammo from dropped weapon, this overflow of ammo get lost into nothingness and wasted for other potential player since if you go over the max ammo, it set back to the max ammo value.

A good fix would be either to block the pickup of weapon's ammo if already at max ammo or something similar.

**Comment by ZehM4tt** [comment]
Yea this is sadly a bad work around as GMod has 9999 as max ammo on the default stuff and you cant modify it, so this is kinda messy to cope with. Ill take a further look into it.

**Comment by ZehM4tt** [comment]
I fixed it to not use more than the player can carry and leaves the rest to the others.
