### ISSUE TITLE
Too far from ChangeLevel

### ISSUE THREAD

**Issue by FluffyEevee** [ZehM4tt/Lambda#8]
If you manage to jump into the trigger_changelevel and past it while there is other players and wait for the timeout, the entity wont be able to changelevel possibly since there is no players inside it.

![ss 2017-01-07 at 02 47 38](https://cloud.githubusercontent.com/assets/9823203/21742126/86c5df7e-d4e8-11e6-8bfb-7abed7bb65d4.png)

**Comment by ZehM4tt** [comment]
Thats a weird one, how did you get past the trigger?

**Comment by FluffyEevee** [comment]
Rocket explosive damage boost, but can't seem to make it happen again, pretty sure it was a conflicting addon.

**Comment by FluffyEevee** [comment]
Seems like it was a conflicting addon, unsure which one tho but it stopped happening after removing all of them, so no 'real' bug here.

**Comment by ZehM4tt** [comment]
Interesting, ill take a look into the those two.

**Comment by ZehM4tt** [comment]
Well I'm going to close this for now, I will keep an eye on it.
